### ISSUE TITLE
Reckoned version 0.1.0-rc.1 has already been released

### ISSUE THREAD

**Issue by codewode** [ajoberstar/reckon#109]
From a release branch let's say release/6.0.x, I have created a feature branch called as feature/api-post-data and then executed the following command 

`./gradlew clean build reckonTagPush -Preckon.stage=rc`
this has created a tag

> 0.1.0-rc.1

feature branch is not yet merged.

then again from release/6.0.x I have created another feature branch called as
feature/api-delete-data and then executed the following command

`./gradlew clean build reckonTagPush -Preckon.stage=rc`
this has created a tag

> 0.2.0-rc.1

again feature branch is not yet merged.

now, I decided to make some changes in feature/api-delete-data and committed them, then I executed again
`./gradlew clean build reckonTagPush -Preckon.stage=rc`

which gives me following error

`FAILURE: Build failed with an exception.
What went wrong:
Could not determine the dependencies of task ':library:compileJava'.
 Could not resolve all dependencies for configuration ':library:compileClasspath'.
    Reckoned version 0.1.0-rc.1 has already been released.`

what am I doing wrong? I was expecting that it will bump up to a new version let's say 
> 0.2.0-rc.2

**Comment by ajoberstar** [comment]
This could be related to #108 or #102. Will have to do some more research.

**Comment by ajoberstar** [comment]
Would you be able to provide a commit log with `--all --graph` so I can see how your commits and branches relate to each other?

I'm not sure if this is the same as either of the two issues I referenced in the previous comment.

**Comment by ajoberstar** [comment]
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.
