### ISSUE TITLE
reckonTagPush hangs when ssh private key file is password protected

### ISSUE THREAD

**Issue by IshanEyepax** [ajoberstar/reckon#110]
When using ssh authentication with git with a password protected private key file reckonTagPush hangs. I assume this is due to an authentication error. when the password is removed it works without issues

**Comment by ajoberstar** [comment]
This is a symptom of ajoberstar/grgit#252. I removed the use of JSch which is a somewhat aging SSH impl in Java with shelling out to the actual `ssh` or `plink` command on the device. However, this doesn't work well when you need a password and the key isn't in an ssh-agent. There's potential that ajoberstar/grgit#283 could be a solution, but not sure if/when I'll have time to look at it.

**Comment by ajoberstar** [comment]
Closing this as its ultimately a grgit issue. You comment on ajoberstar/grgit#283 if you see it as a strong need.
