### ISSUE TITLE
Remove the restriction of clean repo for pushing a final version?

### ISSUE THREAD

**Issue by tsanborn19-zz** [ajoberstar/reckon#128]
I have a system that needs to change the execute permissions on a file when the automated build runs, and unfortunately that file cannot be made executable before that time.

That makes it so that I can't push final versions with this plugin, which is extremely disappointing.

Is there any way to disable the clean repo requirement for final versions?

**Comment by ajoberstar** [comment]
Thank you for your interest in the plugin and for raising this!

Currently, [this isn't configurable](https://github.com/ajoberstar/reckon/blob/5c1cdf3308feab5537ea7f226f0bd68ed4e412a7/reckon-core/src/main/java/org/ajoberstar/reckon/core/Reckoner.java#L58-L60). Right now, I have no plans to provide configurability for these core assumptions of reckon, which isn't to say I'm not sympathetic to the technical limitations that can sometimes prevent people from meeting them. Not ruling it out in the future, but it's a won't fix for now.

**Comment by Cinderhaze** [comment]
@treversan - how does reckon behave if you tell git to ignore file permissions, then change it to executable?

https://github.com/Gizra/KnowledgeBase/wiki/How-to-set-Git-to-ignore-chmod-changes

` git config core.filemode false`

**Comment by tsanborn19-zz** [comment]
Good call @Cinderhaze 

Thanks for the help!

**Comment by dtrunk90** [comment]
Another way is to temporarily ignore the file:
```
git update-index --assume-unchanged "$FILE"
./gradlew doSomeStuff
git update-index --no-assume-unchanged "$FILE"
```

Source: https://gist.github.com/sloanlance/0f0cb5e9819e11d698a26a623bc649f4
