### ISSUE TITLE
reckonTagCreate issue

### ISSUE THREAD

**Issue by erichaominli** [ajoberstar/reckon#130]
Could not evaluate onlyIf predicate for task ':reckonTagCreate'.
> class java.lang.String cannot be cast to class org.ajoberstar.reckon.gradle.ReckonPlugin$DelayedVersion (java.lang.String is in module java.base of loader 'bootstrap'; org.ajoberstar.reckon.gradle.ReckonPlugin$DelayedVersion is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @cdf94b8)

**Comment by ajoberstar** [comment]
You're likely overriding the `project.version` property somewhere in your script. You need to leave that unset, since Reckon sets it and expects it to be a certain class.

**Comment by erichaominli** [comment]
Thank you, it is solved. I made a mistake by writing "version: 1"
