### ISSUE TITLE
Receiving an unclean repo error, although setting stage to an insignificant one

### ISSUE THREAD

**Issue by tmeltser** [ajoberstar/reckon#131]
Hi,

I've just started playing with this plugin (seems very prommissing) and came across the following problem:
In the build.gradle I have:
reckon {
	scopeFromProp()
	stageFromProp('milestone','rc','final')
}
When I run the following command: "gradlew -Preckon.scope=minor -Preckon.stage=milestone tasks" I get the following error: "Cannot release a final or significant stage without a clean repo."

Indeed my repo isn't clean, but why am I getting this error when I clearly indicate an insignificant ("milestone") stage (to the best of my knowledge)?

What am I missing (or is it a bug)?

**Comment by ajoberstar** [comment]
Milestone *is* a significant version. Anything that would be tagged is significant.

**Comment by demo4echo** [comment]
Hi,
First - thanks for replying.
Second - something still isn't clear to me and I couldn't understand it from the examples page as well - what qualifies as an insignificant stage (what is the layout in which I would NOT get this error while having an unclean repo)?

**Comment by tmeltser** [comment]
Hi,
First - thanks for replying.
Second - something still isn't clear to me and I couldn't understand it from the examples page as well - what qualifies as an insignificant stage (what is the layout in which I would NOT get this error while having an unclean repo)?

**Comment by ajoberstar** [comment]
Insignificant _versions_ will include the number of commits since the last final release and the hash of the commit. Significant versions just include the stage name and incremented number within the stage.

Anytime you provide the stage as an input, it will be considered significant.

**Comment by tmeltser** [comment]
OK, the last sentence ("Anytime you provide the stage as an input, it will be considered significant.") did the job, now it's clear and operates as expected (and very well I might add), as well as makes the examples more clear.
I would suggest adding this sentence to the documentation - I think it's an important piece of information that can be skipped and puzzle the operation of the plugin (and again - a very good one!)

10x for the detailed explanation.
