### ISSUE TITLE
Expose the DelayedVersion class to allow extending Reckon from another plugin

### ISSUE THREAD

**Issue by stevendpclark** [ajoberstar/reckon#137]
Hello,

This is a similar request to #94 to expose the internal private static class called DelayedVersion. This would help out to expose isFinal within Kotlin based builds that at the moment can't really call it. I also have another use case, I'm writing a Gradle plugin that would extend some of the Reckon functionality that the company I work for does based on Reckon's calculations. 

Ideally I would be able to apply the Reckon plugin through our custom plugin and extend the DelayedVersion class exposing our own methods while still allowing the existing reckon tasks reckonTagCreate and reckonTagPush to work. 

I'd be happy to create a PR for this but would like to know how you feel about making the current internal DelayedVersion class publicly exposed and opened up for others to extend within their own plugins?

**Comment by ajoberstar** [comment]
0.14.0 now exposes a `Provider<Version>` on the reckon extension.
