### ISSUE TITLE
Tag push fails with latest jgit version

### ISSUE THREAD

**Issue by cmuchinsky** [ajoberstar/reckon#141]
After picking up the latest spotless plugin version I started seeing the following build errors. I suspect this is because of their jgit upgrade to `org.eclipse.jgit:org.eclipse.jgit:5.7.0.202003110725-r`.

```
00:05:13.567 > Task :reckonTagCreate
00:05:13.567 > Task :reckonTagPush FAILED
00:05:13.567 
00:05:13.567 FAILURE: Build failed with an exception.
00:05:13.567 
00:05:13.567 * What went wrong:
00:05:13.567 Execution failed for task ':reckonTagPush'.
00:05:13.567 > java.lang.AbstractMethodError (no error message)
```

**Comment by cmuchinsky** [comment]
A workaround I found is to manually pull in the latest `grgit-gradle` plugin version (`4.0.2`).

**Comment by ajoberstar** [comment]
Either 0.13.2 or 0.14.0 would likely resolve this.
