### ISSUE TITLE
Issue with java9 modules

### ISSUE THREAD

**Issue by ziccardi** [ajoberstar/reckon#144]
I'm trying to configure my java9 project to use reckon. Everything works until I try to specify the module version using:

```gradle
    tasks.compileJava {
        options.javaModuleVersion = provider { project.version }
    }
```

When I add that, I get the following error:
`property 'options.javaModuleVersion' of type java.lang.String as the provider associated with this property returned a value of type org.ajoberstar.reckon.gradle.ReckonPlugin$DelayedVersion`

Any workaround?

Thank you!

**Comment by ajoberstar** [comment]
You'll need to call `toString` for this work.

```
tasks.compileJava {
  options.javaModuleVersion = provider { project.version.toString() }
}
```

**Comment by ajoberstar** [comment]
Closing under the assumption this is resolved. If that's not true and you want to discuss further, please reopen.
