### ISSUE TITLE
reckon fails on "Cannot release a final or significant stage without a clean repo"

### ISSUE THREAD

**Issue by amiryo** [ajoberstar/reckon#149]
Hi ,
I am using reckon which run in jenkins pipeline.
reckon plugin version is '0.13.0'
grgit plugin version is '4.1.0'
gradle version is '6.6.1'

The plugin is invoked with scope=minor and stage=rc

The issue:
plugin fails on dirty repo while repo seems to be clean according to the checks I did:  
Running "git status", "git clean --dry-run", "git diff --shortstat" , ""  commands before and after invoking reckon plugin. They are all showing clean repo.

Any prompt assistance would be appreciated a lot.

**Comment by amiryo** [comment]
Hi,
can you please advise how to solve the issue ?

Thanks
Amir

**Comment by amiryo** [comment]
I closed the issue by mistake....still open

Thanks 
Amir

**Comment by tmeltser** [comment]
Hi,
I have also encountered this problem and would be very happy to get some guidenss on the subject.

Tiran.

**Comment by stephenlawrence** [comment]
You need to have a clean source tree with no uncommitted changes.

**Comment by amiryo** [comment]
Hi,
I found the file that dynamically updated during the build and  caused the
unclean status
Thank you for your support!

**Comment by pmorch** [comment]
So this can be closed, then? If so, please close it, amiryo.

**Comment by amiryo** [comment]
Done
