### ISSUE TITLE
Check if a version `isSignificant`

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [ajoberstar/reckon#156]
I would like to do:

```
fun Project.isSignificant(): Boolean {
    return version.isSignificant() // isSignificant() doesnt exist because version is `Any`
}
```

But I can't cast the version property to a reckon version because it is a `DelayedVersion` which is a private class.

Is there any way to check if the version is significant?

**Comment by ajoberstar** [comment]
Fixed via #169
