### ISSUE TITLE
 Could not find org.ajoberstar.grgit:grgit-core:4.1.1-rc.3.

### ISSUE THREAD

**Issue by adarzulfu** [ajoberstar/reckon#163]
Hi, This morning there is an error thrown while running a build

<img width="1160" alt="Screen Shot 2021-12-01 at 09 36 50" src="https://user-images.githubusercontent.com/22280504/144184607-375b2eb4-7e66-4f1c-890b-011d25458c99.png">

Is there something that I can do?

**Comment by brnhffmnn** [comment]
Coiuld this be related to ajoberstar/grgit#339 ?

**Comment by ajoberstar** [comment]
Fixed for real in 0.13.2
