### ISSUE TITLE
Forcing tag even with an unclean repo

### ISSUE THREAD

**Issue by djechelon** [ajoberstar/reckon#166]
I understand that it is a **tremendously bad idea**, but I am currently fighting with a potential bug in [Azure DevOps Gradle Task](https://github.com/microsoft/azure-pipelines-tasks/issues/15668)

Basically, whenever Azure DevOps runs Gradle, for reasons unkown to me it will overwrite the `gradlew` script.

I would like to ask for a feature, namely a closure or -P expression, that allows `reckon` to go ahead with tagging even if the repository is dirty.

That is generally a bad idea, I am aware of the normal risks. It's just a [**porkaround**](https://www.urbandictionary.com/define.php?term=porkaround)

**Comment by ajoberstar** [comment]
Looking at the upstream issue you linked, it appears you've resolved the concern. Given that, I'll close this out.
