### ISSUE TITLE
Plugin's dependency on JCenter 

### ISSUE THREAD

**Issue by chagen19** [ajoberstar/reckon#167]
There seems to be a JCenter outage today which is causing a failure with the reckon plugin. Is there a workaround?

My configuration:
```
plugins {
	id 'java'
	id 'idea'
	id 'org.ajoberstar.reckon' version '0.13.1'
}
reckon {
	scopeFromProp()
	stageFromProp('beta', 'rc', 'final')
}
```
Error message:
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.eclipse.jgit:org.eclipse.jgit:[5.0,6.0).
     Required by:
         project : > org.ajoberstar.reckon:org.ajoberstar.reckon.gradle.plugin:0.13.1 > org.ajoberstar.reckon:reckon-gradle:0.13.1
      > Failed to list versions for org.eclipse.jgit:org.eclipse.jgit.
         > Unable to load Maven meta-data from https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
   > Could not resolve com.google.guava:guava:latest.release.
     Required by:
         project : > org.ajoberstar.reckon:org.ajoberstar.reckon.gradle.plugin:0.13.1 > org.ajoberstar.reckon:reckon-gradle:0.13.1
      > Skipped due to earlier error

**Comment by MrBergin** [comment]
You're probably aware now, but just in case not it was resolved a few hours ago:

https://stackoverflow.com/questions/70687342/jcenter-bintray-com-is-down-error-502-bad-gateway

I can confirm this plugin's working for me again now.

**Comment by rohgar** [comment]
The outage is resolved, but is there a way to make this plugin work offline? (assuming I don't have it in my Gradle cache)

**Comment by ajoberstar** [comment]
This was on Gradle's side: https://blog.gradle.org/plugins-jcenter
