### ISSUE TITLE
`ReckonExtension.setDefaultInferredScope` could take `org.ajoberstar.reckon.core.Scope`

### ISSUE THREAD

**Issue by x80486** [ajoberstar/reckon#175]
I think `ReckonExtension.setDefaultInferredScope/1` could be overloaded to accept `org.ajoberstar.reckon.core.Scope` as well — unless this one is not supposed to be used somehow.

I'm currently using it like:

```groovy
reckon {
  setDefaultInferredScope(Scope.PATCH as String)
  setScopeCalc(calcScopeFromProp())
  setStageCalc(calcStageFromProp())
  stages("beta", "rc", "final")
}
```

...but I think accepting the `enum` as well is better because using constant is less error prone, and can provide a (very) small performance advantage.

**Comment by ajoberstar** [comment]
Overload seems fine to me. Personally think the need to do an import to get the enum approach to work is going to be more error prone than using the string.
