### ISSUE TITLE
Gradle plugins register/portal is not in sync with GitHub releases

### ISSUE THREAD

**Issue by x80486** [ajoberstar/reckon#176]
Somehow the last released version in the Gradle plugins portal/register is `0.13.2-rc.4` (which is not even in GitHub as far as I can tell). The last release in GitHub is `0.16.1`.

I think most people will use the Gradle portal before coming to GitHub. Not sure how anything gets into that portal, but somehow something in not in sync with it.

**Comment by mjstrasser** [comment]
[The README](/ajoberstar/reckon/#newest-versions-are-on-maven-central) states that recent versions are on Maven Central.

This configuration worked for me (Kotlin DSL). In `settings.gradle.kts`:
```kotlin
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}
```
**NB:** Specify `mavenCentral()` first.

Then, in `build.gradle.kts`:
```kotlin
plugins {
    id("org.ajoberstar.reckon") version "0.16.1"
}
```

Hope this helps!

**Comment by ajoberstar** [comment]
@x80486 My rationale is described [in one of grgit's issues](https://github.com/ajoberstar/grgit/issues/359).

As for adding `mavenCentral()` to your `pluginManagement` that shouldn't be necessary. Gradle's plugin portal proxies Central, so you will be able to pick up the plugin without customizing your `pluginManagement.repositories`. That said I do find the portal to be a tad brittle sometimes, so using central directly can sometimes be useful.

**Comment by x80486** [comment]
What I tried to say is that if someone browse over Gradle's portal, there is no `0.16.1` version, but `0.13.2-rc.4` as latest.

![image](https://user-images.githubusercontent.com/34633617/160290035-fcd38520-11b1-40b5-b28c-3c26db376eee.png)

Thus, I don't know how do you synchronize that gap between the Gradle portal and GitHub releases.

**Comment by ajoberstar** [comment]
Right, the portal UI will not show that newer versions of the plugin are available. That requires the API incantations that the `com.gradle.plugin-publish` plugin does. However, the plugin portal repo proxies JCenter and Maven Central, so anything available in those two is available without extra configuration in your build.

For example, this URL will download the 0.16.1 POM, even though in the UI it doesn't look like it's available.

https://plugins.gradle.org/m2/org/ajoberstar/reckon/reckon-gradle/0.16.1/reckon-gradle-0.16.1.pom

This means that you do not need to customize your `pluginManagement.repositories` to get the latest version of reckon.

I understand that it can be confusing for a user that the latest version isn't indicated in the portal UI, but the reasons outlined in that grgit issue override that convenience for me as a maintainer.

**Comment by x80486** [comment]
OK, great. I just didn't know if you were aware of that — or not. I can close this one :sunglasses:
