### ISSUE TITLE
Plugin [id: 'org.ajoberstar.defaults.gradle-plugin', version: '0.17.1'] was not found

### ISSUE THREAD

**Issue by lalitc113** [ajoberstar/reckon#191]
Hi,
I am not sure if this is right place to raise this issue but
I am new to this plugin and while running gradlew build I am getting below error 

./gradlew --info build -Preckon.scope=minor -Preckon.stage=milestone

* Where:
build.gradle.kts' line: 1

* What went wrong:
Plugin [id: 'org.ajoberstar.defaults.gradle-plugin', version: '0.17.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.ajoberstar.defaults.gradle-plugin:org.ajoberstar.defaults.gradle-plugin.gradle.plugin:0.17.1')
  Searched in the following repositories:
    MavenRepo

tried other version also 0.16.0 and 0.16.1 but still getting same error

**Comment by ajoberstar** [comment]
What does your `settings.gradle` `pluginManagement` block and/or `build.gradle` `buildscript` block look like?

You'll need either the default Gradle plugin portal or Maven central repo to get reckon.

**Comment by lalitc113** [comment]
thanks for your answer yes it got blocked...
