### ISSUE TITLE
Provide a way to override the behavior of major commit messages for pre-1.0.0 versions

### ISSUE THREAD

**Issue by dalewking** [ajoberstar/reckon#204]
> In order to promote the convention of using major: My message for breaking changes, before 1.0.0 a major in a commit message will be read as minor.

I understand the reasoning for that but, that puts me in a catch-22 that I have no good way to promote a library to 1.0.0 status. The docs say that:

> The goal is to promote you explicitly documenting breaking changes in your commit logs, while requiring the actual 1.0.0 version bump to come via an override with -Preckon.scope=major.

But that assumes that the developer is releasing and pushing things to the repo directly. In good development practice pushing directly to a main branch is forbidden and the only way to change main is via pull requests that are built in a CI/CD build.

The question then is how can one then through a pull request move the library to 1.0.0? The only way I can see is to do a PR that forces scope to major, merge it, do another PR that undoes the forcing of scope and merge that. That is not a good developer experience. There should be an option to disable the pre-1.0.0 behavior or perhaps set a minimum version

**Comment by dalewking** [comment]
My workaround for now:
```
    // This is a workaround for this issue: https://github.com/ajoberstar/reckon/issues/204
    // It can be removed after 1.0.0 is released
    fun forceMajorReleaseFromPreRelease(forceRelease: Boolean) =
        ScopeCalculator { inventory ->
            Optional.ofNullable(
                Scope.MAJOR.takeIf {
                    forceRelease && inventory.baseNormal < Version.valueOf("1.0.0")
                }
            )
        }

    setScopeCalc(
        forceMajorReleaseFromPreRelease(true)
            .or(calcScopeFromCommitMessages()),
    )
```

**Comment by dalewking** [comment]
The way I see this working would be an optional parameter to `calcScopeFromCommitMessages` that specifies whether to allow commit messages to upgrade to 1.0.0

**Comment by ajoberstar** [comment]
Planning to release soon and you'll have two options:

- Use the existing `calcScopeFromCommitMessages()` which now allows a `major!: My message` prefix to force a 1.0.0 bump
- Use `calcScopeFromCommitMessageParser(...)` with a custom parser of the form `(String commitMessage, boolean preV1) -> Optional<Scope>`

**Comment by dalewking** [comment]
Thanks for changing this, though I have switched to
https://github.com/jmongard/Git.SemVersioning.Gradle to get true
conventional commits and changelog generation
