### ISSUE TITLE
Investigate parallel behavior

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/reckon#45]
Parallel versions behavior may be too aggressive right now.

**Comment by ieugen** [comment]
Hi. Is this related to #54 ?

**Comment by ajoberstar** [comment]
No, this is tied to how reckon decides if a parallel version is being developed. The tag parsing related to #54 is independent from this.

**Comment by ajoberstar** [comment]
There are still weaknesses here, but I'll let specific issues speak for themselves.
