### ISSUE TITLE
Deprecation warning for Task.dependsOnTaskDidWork()

### ISSUE THREAD

**Issue by valter-silva-au** [ajoberstar/reckon#51]
```
gradle reckonTagPush

> Task :reckonTagCreate
Reckoned version: 0.5.0-milestone.0.5+2c00c58855390f968028a13991bf35b5a442a557

> Task :reckonTagPush
The Task.dependsOnTaskDidWork() method has been deprecated and is scheduled to be removed in Gradle 5.0. Instead, check the value of "didWork()" for each task, or declare the task inputs and outputs and let Gradle decide what needs to be run.
```

Gradle version

```
gradle --version

------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64
```

Looking at the code, I think the error is being called [here](https://github.com/ajoberstar/reckon/blob/79ac902bbde18b4e22cc9c37b6348c389333e453/reckon-gradle/src/main/java/org/ajoberstar/reckon/gradle/ReckonPlugin.java#L96).

I'm trying to workaround this issue by tagging my branches manually. 
However, I think in order for the plugin to work properly, it needs to use the tasks `createTag` and `pushTag`, right?

My [repository is public](https://github.com/tech-vsilva/gaf), I'm testing your solution for versioning artifacts using a Gradle plugin. So in order to reproduce, just clone my repository and run `./gradlew reckonTagPush`.

Thank you very much for your effort in this amazing plugin! 😃

**Comment by ajoberstar** [comment]
Thanks for pointing this out, should be pretty easy to resolve (have a different plugin I had to fix this in recently).
