### ISSUE TITLE
Document expected default tag format

### ISSUE THREAD

**Issue by eaaltonen** [ajoberstar/reckon#55]
I tried reckon `0.3.0` on a project having the following tags:
```
v0.3
v0.4
v0.4.1
v0.5
v0.5.1
v0.5.2
```

based on the intructions on the **Readme.md**. However, I do not get the expected reckon output. I think it would be good to document (_say, two examples_) what kind of tags the project expects by default.

**Comment by ajoberstar** [comment]
Good point, I'll plan to provide some more info on this in the docs.

For now, the short version is that if it's a valid SemVer string (optionally, prefixed with a `v`), it will be used by the algorithm. If not, it's ignored. Those 2 part numbers, e.g. `v0.3`, aren't valid SemVer strings, so they wouldn't be used.
