### ISSUE TITLE
[Fug / Improvement] Please Improve error message on invalid passed reckon.scope 

### ISSUE THREAD

**Issue by childnode** [ajoberstar/reckon#57]
since `-Preckon.stage=sdf` provides a helpful hint
```
* What went wrong:
> Stage "sdf" is not one of: [rc, final]
```

`-Preckon.scope=sdf` only provides message
```
> No enum constant org.ajoberstar.reckon.core.Scope.SDF
```

instead of expected
```
> Scope "sdf" is not one of: [patch, minor, major]
```

**Comment by childnode** [comment]
https://github.com/ajoberstar/reckon/blob/b23e2914fe6ed155a83cb9c4046174049b67fd55/reckon-core/src/main/java/org/ajoberstar/reckon/core/strategy/StagePreReleaseStrategy.java#L54
https://github.com/ajoberstar/reckon/blob/b23e2914fe6ed155a83cb9c4046174049b67fd55/reckon-core/src/main/java/org/ajoberstar/reckon/core/strategy/ScopeNormalStrategy.java#L40

**Comment by ajoberstar** [comment]
Agreed. Thanks for pointing this out!
