### ISSUE TITLE
doesn't work without manual plugin dep to grgit 

### ISSUE THREAD

**Issue by childnode** [ajoberstar/reckon#62]
it's well ... undocumented ... that reckon is not working unless you add `  id 'org.ajoberstar.grgit' version '<version>' ` as in the example, else you just get `No VCS found/configured. Version will be 'unspecified'.`. https://github.com/ajoberstar/reckon/blob/980bb8db106b1ccac2f22e18becf53a0eb555bb9/reckon-gradle/src/main/java/org/ajoberstar/reckon/gradle/ReckonPlugin.java#L43

**Comment by ajoberstar** [comment]
Yep, this is a documentation hole. Thanks for catching. It will be part of my #58 updates.
