### ISSUE TITLE
Indicate uncommitted changes in version numbers

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/reckon#67]
Versions should indicate that there are uncommitted changes.

- [x] A VCS with uncommitted changes should not be allowed to make a _significant_ version (or make a tag)
- [x] A VCS with uncommitted changes should not follow the _rebuild_ logic of reusing a tag on the `HEAD` commit
- [x] A VCS with uncommitted changes should indicate in stage strategy's build component (e.g. `1.0.0-stage.2+abcdef.uncommitted`

Reported in #66

**Comment by roguexz** [comment]
Thank you. Looking forward to testing the next release.
