### ISSUE TITLE
rebuilding claimed version snapshot from historic commit

### ISSUE THREAD

**Issue by esz** [ajoberstar/reckon#78]
Currently, reckon doesn't allow me to rebuild historic snapshots from old commits (with clean repo) if the subsequent normal version has already been released. Let's assume the following project setup:

Plugin settings:
```
reckon {
	normal = scopeFromProp()
	preRelease = snapshotFromProp()
}
```
Repo:
```
                      0.2.0
                        |
0-------X-------0-------0----...
                |\
                | \-----0----...
                |       |
              0.1.0     |
                      0.1.1
```

Now I want to rebuild `X` from a clean repo state, but reckon complains, saying:
```
* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Reckoned target normal version 0.1.0 has already been released.
```

In my opinion it should be possible to rebuild `0.1.0-SNAPSHOT` from `X` when there are no local changes present and the `0.0.1` Tag is the lowest normal version within the successor commits reachable from `X`. 

Of course I can still use `-Preckon.scope=major` or  `-Preckon.scope=patch` to build `1.0.0-SNAPSHOT` or `0.0.1-SNAPSHOT` in this example, if the subsequent normals have not been claimed yet.

But the behavior above can be particularly painful, since I am not able to import old revisions (e.g. when im `git bisect`ing) of my project into Eclipse using buildship with the build failing.

I wrote a small (failing) test, illustrating the expected behavior:
esz/reckon@dbe10e34ac53a514cb6b6b750e9209c6673c4d01

What do you think about that? Am I just overlooking some valid reason for this restrictive behavior? If you think this would be a useful addition, I'd contribute happily!

**Comment by ajoberstar** [comment]
I've defaulted to being restrictive where I wasn't sure if the behavior should be allowed.

I agree with you that this should be allowed, though I don't know if it's a simple change.

My initial thoughts are that the behavior should be:

- For any significant tagged version in claimed you can only rebuild it if you're on the same commit.
- For an insignificant version you can rebuild it only if that commit is in the history of the claimed version.
- All other scenarios that currently fail should still fail.

**Comment by ajoberstar** [comment]
If you want to check out [0.7.0-rc.1](https://github.com/ajoberstar/reckon/releases/tag/0.7.0-rc.1) this should work now. Thanks for opening and providing a test!

**Comment by esz** [comment]
Hi, just tried [0.7.0](../releases/tag/0.7.0)
Works like a charm! Thank you!
