### ISSUE TITLE
Use an abbreviated commit hash in the build metadata

### ISSUE THREAD

**Issue by jco2641** [ajoberstar/reckon#86]
What is the rationale behind using the full commit hash in the insignificant versions, vs the abbreviated commit hash git provides?
As I understand it, the abbreviated hash will expose enough characters to ensure it is unambiguous for referring to a commit.

**Comment by ajoberstar** [comment]
This was partly based on the way Grgit's abbreviated hash is computed currently (it's just a straight substring). However, there is a more reliable option in JGit that I could use, so I've opened an issue (ajoberstar/grgit#238) to enhance that.

Given that improvement and the unlikelihood of even a 7 character hash having a collision, I'd be fine switching these to abbreviated ones. It would be more user friendly.
