### ISSUE TITLE
ReckonTagCreate failed

### ISSUE THREAD

**Issue by jco2641** [ajoberstar/reckon#87]
This is the first time I've attempted to tag a build with reckon.  
The build process without tagging works perfectly for naming the artifacts.

Command line:
$ ./gradlew reckonTagPush -Preckon.scope=patch -Preckon.stage=beta --info --stacktrace

Error output:
> Task :reckonTagCreate FAILED
:reckonTagCreate (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.0 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Could not evaluate onlyIf predicate for task ':reckonTagCreate'.
> org.codehaus.groovy.runtime.GStringImpl cannot be cast to org.ajoberstar.reckon.gradle.ReckonPlugin$DelayedVersion

Full output:
https://gist.github.com/jco2641/ea840539d51b6614a109e08833fddb0e

Build.gradle file:
https://github.com/jco2641/Thaumic_Computers/blob/master/build.gradle

**Comment by jco2641** [comment]
I suspect it might be because I am messing with project.version after it is set by reckon, so it is not a Version object anymore.

**Comment by jco2641** [comment]
That was the source of the problem, no issue with your project.

**Comment by erichaominli** [comment]
I have the same problem. Could you share the solution?

**Comment by jco2641** [comment]
@EricHaomin 
The cause was in my comments and closure.  I was setting project.version to a string after reckon was setting it to an object.  I took out or changed the string manipulation i was doing and it went away.
