### ISSUE TITLE
./gradlew build not outputting the version number

### ISSUE THREAD

**Issue by jpzweig** [ajoberstar/reckon#92]
-bash-4.2$ ./gradlew build

> Configure project :
plugin: org.gradle.api.plugins.HelpTasksPlugin@571ff080
plugin: org.ajoberstar.grgit.gradle.GrgitPlugin@9dac5e
plugin: org.ajoberstar.reckon.gradle.ReckonPlugin@16ed2a10

BUILD SUCCESSFUL in 4s
12 actionable tasks: 12 executed
-----------------------------------------------------------------------

I am running a build and am not getting the version number as shown in the tutorial. I also tried to clean the project before building and after adding the plugin and the version number still is not appearing. Any idea how to get the version number to show by running "./gradlew build" ?

Thanks!

**Comment by ajoberstar** [comment]
The version should print the first time something tries to call toString on it. Usually this is something like your JAR or some other publishing related config. Can you share any more of your build file to help narrow this down?

**Comment by jpzweig** [comment]
Just solved the issue. Thank you so much!
