### ISSUE TITLE
Expose version in build

### ISSUE THREAD

**Issue by raniejade** [ajoberstar/reckon#94]
I would like to publish to a bintray repo based on the version, something like:

```gradle
def bintrayRepo = 'spek-dev'
if (rootProject.reckon.getVersion().isFinal()) {
    bintrayRepo = 'spek'
}

bintray {
    user = bintrayUser
    key = bintrayApiKey
    publish = false
    dryRun = true
    pkg {
        repo = bintrayRepo
        desc = "Test framework for Kotlin"
        name = 'spek2'
        userOrg = 'spekframework'
        licenses = ['BSD New']
        labels = ['kotlin', 'testing']
        vcsUrl = 'https://github.com/spekframework/spek.git'

        githubRepo = 'spekframework/spek'


        version {
            name = rootProject.version
        }
    }

    publications = artifacts
}
```

`ReckonExtension` already have `getVersion` but it's package-private.

**Comment by ajoberstar** [comment]
You should be able to do this with the `getVersion` method added on the `project.version`. 

```
project.version.version.isFinal()
```

[Source](https://github.com/ajoberstar/reckon/blob/527bed12eff8c4eb27783ab183819f93d3fa65fc/reckon-gradle/src/main/java/org/ajoberstar/reckon/gradle/ReckonPlugin.java#L74)

**Comment by ajoberstar** [comment]
Closing under the assumption this is resolved. If that's not true and you want to discuss further, please reopen.

**Comment by atali** [comment]
Unfortunately it's not working

![image](https://user-images.githubusercontent.com/369628/63068870-cea02980-bee2-11e9-827d-3150651364e9.png)
