### ISSUE TITLE
Add removal of the 'version' to the documentation

### ISSUE THREAD

**Issue by christopheralanjones** [ajoberstar/reckon#96]
I discovered, quite by accident, that having a 'version' property defined in the build.gradle will cause reckon to basically ignore it's processing. That makes sense but it might be useful to explicitly call out that requirement in the documentation. I know there's a whole section that says to get the version number out of the build file, but it's more conceptual in its content and doesn't mention this as a requirement.

I'll apologize in advance if I simply didn't do an adequate job of RTFM.

**Comment by ajoberstar** [comment]
If you have a spot in mind where this should go, feel free to send a PR in. Otherwise I'll catch this in the next round of updates. Thanks for sending this in.
