### ISSUE TITLE
Applying the plugin from a script plugin

### ISSUE THREAD

**Issue by bmuschko** [ajoberstar/reckon#97]
Gradle still doesn't support applying a plugin by ID from a script plugin. For example I have the following code in `release.gradle`:

```
buildscript {
    repositories {
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }

    dependencies {
        classpath 'org.ajoberstar.reckon:reckon-gradle:0.8.0'
    }
}

apply plugin: org.ajoberstar.reckon.gradle.ReckonPlugin
```

Internally, the reckon plugin tries to [apply the plugin with ID `org.ajoberstar.grgit`](https://github.com/ajoberstar/reckon/blob/master/reckon-gradle/src/main/java/org/ajoberstar/reckon/gradle/ReckonPlugin.java#L24). I believe this doesn't work in script plugins as you have to apply the plugin by type. The published metadata should probably include the `org.ajoberstar.grgit` dependency. It is a requirement for this plugin to work properly. Am I missing something?

**Comment by ajoberstar** [comment]
I do have a compile dependency on grgit. I presume the issue here is that I'm applying by ID, instead of by class name?

**Comment by bmuschko** [comment]
That's my guess.

**Comment by rgozim** [comment]
Just a heads, up I saw the same issue when using:

```kotlin
   apply<ReckonPlugin>()
```

To fix it:

```kotlin
    apply<GrgitPlugin>() // Applying grgit first
    apply<ReckonPlugin>()
```

**Comment by kevin-maskell-moody** [comment]
I'm fairly certain that this is related to this. Perhaps, @bmuschko can clarify. I'm developing a kotlin plugin that applies reckon, by class (maybe this is the same as applying via a script plugin?), and configures the extension.

This seemed to be working great in test projects and whatnot, where I was blindly applying the reckon plugin, and my plugin had an `api` dependency on both `grgit-gradle` and `reckon-gradle`. I'm not 100% at what point this stopped working, but it should...

```
val reckonPlugin = ReckonPlugin::class.java
if (!rootProject.pluginManager.hasPlugin(reckonPlugin.name)) {
    rootProject.pluginManager.apply(reckonPlugin)
    configureReckon(rootProject)
}
```

Suddenly, started seeing:

> Failed to apply plugin [class 'org.ajoberstar.reckon.gradle.ReckonPlugin']
> Plugin with id 'org.ajoberstar.grgit' not found.

I attempted to directly apply `grgit-gradle` and added the following to see what was actually applied:

```
logger.info("Applying reckon gradle plugin to root project")
logger.info("Is org.ajoberstar.grgit applied? - ${rootProject.pluginManager.hasPlugin("org.ajoberstar.grgit")}")
rootProject.plugins.forEach {
    println("Plugin - $it")
}
```

Got the following output:

> Applying reckon gradle plugin to root project
> Is org.ajoberstar.grgit applied? - true
> Plugin - org.gradle.plugins.ide.idea.IdeaPlugin@1f815831
> ...
> Plugin - org.ajoberstar.grgit.gradle.GrgitPlugin@4887324a

But, I still see the same error.

**Comment by kevin-maskell-moody** [comment]
So, I forked reckon and made the simple change of applying `grgit-gradle` via the plugin's class name. That resolves the issue. I now see an innocuous warning:

> Is org.ajoberstar.grgit applied? - false
> Plugin - ...
> Project :xyz already has a grgit property. Remove org.ajoberstar.grgit from either :xyz or :xyz.

I didn't dig much to see where this was coming from. But, it looks like there are a few bad checks going on and you can easily move to applying the plugin by class name.

Should I create a pull request for this small change or leave it to you?

`ReckonPlugin.java:25`
```
Class grgitPlugin = GrgitPlugin.class;
project.getPluginManager().apply(grgitPlugin);
```
